### ISSUE TITLE
how i can write logs in file?

### ISSUE THREAD

**Issue by prtolem** [mostepunk/fastapi-json-log#1]
i checked code and didnt find anything about it. I try to did it myself with add the filename in loguru.logger but it didnt work right, it write simple logs not json
how i can do it?
thanks

**Comment by mostepunk** [comment]
Hi @prtolem !

Nice feature, added for you :)

[Here added file handler](https://github.com/mostepunk/fastapi-json-log/blob/master/app/core/logging.py#L154-L158) and [here is settings for it](https://github.com/mostepunk/fastapi-json-log/blob/master/app/core/logging.py#L122-L131)

On my previous work logs were collecting in Kubenetes from stdout, and that's why I don't think about write to file.

Pull project again and try.
