### ISSUE TITLE
Write logs to file

### ISSUE THREAD

**Issue by oObelix** [mostepunk/fastapi-json-log#2]
Hello!
How to setup this logger to save logs to file(s) with names by dates and deleting old files?

**Comment by mostepunk** [comment]
Hello @oObelix 
For this stuff you should use [TIMED ROTATING FILE HANDLER](https://cppsecrets.com/users/1357411510911410511610510350484964103109971051084699111109/Python-Timed-Rotating-File-Logging-Handlers.php) instead of [my FileHandler](https://github.com/mostepunk/fastapi-json-log/blob/master/app/core/logging.py#L157).
I think it will help you
